### ISSUE TITLE
v4.0.0 发布了吗？

### ISSUE THREAD

**Issue by xieyihao** [kidney/guido#8]
1. v4.0.0 发布了吗， 可用于生产环境了？

1. v4里是可以扩展guido的webpack配置了？
[createWebpackConfig.js](https://github.com/zuzucheFE/guido/blob/62a9e222fdd2afbd9884425dc2d1cbd5c55ff3e6/lib/utils/createWebpackConfig.js#L35-L45)
```
if (TypeOf.isObject(appWebpackConfig)) {
	config = mergeWebpackConfig(config, appWebpackConfig);
	config = addModules(config);
} else if (TypeOf.isFunction(appWebpackConfig)) {
	config = addModules(config);
	config = appWebpackConfig(config);
}
```

**Comment by khronosleung** [comment]
1、beta版本已可应用于生产环境，目前在处理文档编写工作，releases预计这月内发出
2、支持扩展
